version: '3.8'

x-container: &container
  restart: always
  logging:
    options:
      max-size: '100m'
      max-file: '3'
    driver: json-file

x-container-web: &container-server
  <<: *container
  tty: true
  working_dir: /srv/app/
  env_file:
    - .env
  volumes:
    - .:/srv/app
  environment:
    DJANGO_SETTINGS_MODULE: "backend.settings"
    PYTHONIOENCODING: "UTF-8"
    LANG: "C.UTF-8"
    LC_ALL: "C.UTF-8"

services:
  api:
    <<: *container-server
    build: .
    command: [ "gunicorn", "backend.wsgi:application", "-c", "conf/gunicorn.conf.py", "--reload" ]
    ports:
      - "8001:8000"
