# Generated by Django 5.0.2 on 2024-06-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_user_openai_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
