# Generated by Django 5.0.2 on 2024-06-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_remove_user_telegram_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
