# Generated by Django 5.0.2 on 2024-06-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_user_telegram_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_budget',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
