# Generated by Django 5.0.2 on 2024-06-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_integration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
