# Generated by Django 5.0.4 on 2024-05-06 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("human_message", models.TextField()),
                ("ai_message", models.TextField(blank=True, default="")),
                ("json_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("system_message", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_name", models.CharField(max_length=255)),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_model",
                    models.CharField(
                        choices=[
                            ("gpt-4-turbo", "Gpt 4 Turbo"),
                            ("llama-3", "Llama 3"),
                        ],
                        default="gpt-4-turbo",
                        max_length=255,
                    ),
                ),
                ("previous_messages", models.JSONField(blank=True, default=list)),
                ("system_message", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="SystemMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("prompt", models.TextField()),
            ],
        ),
    ]
