# Generated by Django 5.0.2 on 2024-05-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_name',
            field=models.CharField(default='New chat', max_length=255),
        ),
    ]
