# Generated by Django 5.0.2 on 2024-05-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatsession_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_name',
            field=models.CharField(default='New chat', max_length=500),
        ),
        migrations.AlterField(
            model_name='systemmessage',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
