# Generated by Django 5.0.2 on 2024-05-12 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Recurring', 'Recurring')], default='Regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Food & Drinks', 'Food'), ('Entertainment', 'Entertainment'), ('Utilities & Bills', 'Utilities'), ('Health & Wellness', 'Health'), ('Shopping', 'Shopping'), ('Education', 'Education'), ('Gifts', 'Gift'), ('Rent', 'Rent'), ('Subscription', 'Subscription'), ('Other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Food & Drinks', 'Food'), ('Entertainment', 'Entertainment'), ('Utilities & Bills', 'Utilities'), ('Health & Wellness', 'Health'), ('Shopping', 'Shopping'), ('Education', 'Education'), ('Gifts', 'Gift'), ('Rent', 'Rent'), ('Subscription', 'Subscription'), ('Other', 'Other')], max_length=20)),
                ('charge_day', models.IntegerField()),
                ('frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('RUB', 'Rub'), ('AED', 'Aed'), ('GBP', 'Gbp'), ('AUD', 'Aud'), ('KZT', 'Kzt')], default='USD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
