# Generated by Django 5.0.2 on 2024-05-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly')], default='Monthly', max_length=20),
        ),
    ]
