# Generated by Django 5.0.2 on 2024-05-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_recurringtransaction_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default='2024-05-15'),
        ),
    ]
