# Generated by Django 5.0.2 on 2024-05-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='next_charge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
